// <auto-generated />
using System.Collections.Generic;
using Memoirist_V2.WriterService.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Memoirist_V2.WriterService.Migrations
{
    [DbContext(typeof(WriterDbContext))]
    [Migration("20241110151914_YarpAuthenMigration_v1")]
    partial class YarpAuthenMigration_v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Memoirist_V2.WriterService.Models.Writer", b =>
                {
                    b.Property<int>("WriterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WriterId"));

                    b.Property<string>("Account")
                        .HasColumnType("text");

                    b.Property<List<int>>("ListFollower")
                        .HasColumnType("integer[]");

                    b.Property<List<int>>("ListFollowing")
                        .HasColumnType("integer[]");

                    b.Property<List<int>>("ListFollowingStoryId")
                        .HasColumnType("integer[]");

                    b.Property<List<int>>("ListPostId")
                        .HasColumnType("integer[]");

                    b.Property<List<int>>("ListStoryId")
                        .HasColumnType("integer[]");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("WriterAvatar")
                        .HasColumnType("text");

                    b.Property<string>("WriterBio")
                        .HasColumnType("text");

                    b.Property<string>("WriterBirthday")
                        .HasColumnType("text");

                    b.Property<string>("WriterEmail")
                        .HasColumnType("text");

                    b.Property<string>("WriterFullname")
                        .HasColumnType("text");

                    b.Property<string>("WriterGender")
                        .HasColumnType("text");

                    b.Property<string>("WriterPhone")
                        .HasColumnType("text");

                    b.Property<string>("WriterUsername")
                        .HasColumnType("text");

                    b.HasKey("WriterId");

                    b.ToTable("Writers");
                });
#pragma warning restore 612, 618
        }
    }
}
